import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Contact from '../components/Contact'
import Intro from '../components/Intro'
import NavBar from '../components/NavBar'
import Projects from '../components/Projects'
import Technologies from '../components/Technologies'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBar />
      <Intro />
      <About />
      <Technologies />
      <Projects />
      <Contact />
    </div>
  )
}
